a = input('Digite ')
print('O tipo é ', type(a))
print('Espaços ', a.isspace())
print('Numerico ', a.isnumeric())
print('Alfabetico ', a.isalpha())
print('Alfanumerico ', a.isalnum())
print('Maiuscula ', a.isupper())
print('Minuscula ', a.islower())
print('Capitalizada ',a.istitle())
