
nome = str(input('Digite o nome \n'))
print ('O nome é: ', nome)
print ('Maiúsculo: ', nome.upper())
print ('Minúsculo ', nome.lower())
div = nome.split()
jun = ''.join(div)
print (div)
print (len(nome))
print(jun)
print (len(jun))
print (len(div[0]))
