
nome = str(input('Digite o nome \n')).strip()
print ('O nome é: ', nome)
print ('Maiúsculo: ', nome.upper())
print ('Minúsculo ', nome.lower())
print ('*****************************')
print ('Total {}'.format(len(nome) - nome.count(' ')))
div = nome.split()
jun = ''.join(div)
print (div)
print (len(nome))
print(jun)
print (len(jun))
print (len(div[0]))
print ('*****************************')
print ('Primeiro nome tem ', nome.find(' '))
